'''
Problem 12
The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?



'''

import prime
import math

primes = prime.sieve(100)
not_found = True
triangle_num =3 
counter_num =3
while not_found:
	factored_num = triangle_num
	factor_counter = 1
	if not prime.miller_rabin(triangle_num):
		for i in primes:
			factor_pow=0
			while factored_num%i ==0:
				factor_pow+=1
				factored_num=factored_num/i
			factor_counter*=(factor_pow+1)
			if factored_num ==1 :
				break
		if factor_counter >500:
			print triangle_num
			not_found = False
	triangle_num+= counter_num
	counter_num+=1

