#Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#By starting with 1 and 2, the first 10 terms will be:

#		1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
#find the sum of the even-valued terms.

answer = 2
j = 1
k = 2
i = 3

while i<4000000:
	
	if i % 2 == 0:
		answer+=i

	j = k+i
	k = i
	i = j

print answer